---
categories:  
- ""    #the front matter should be like the one found in, e.g., blog2.md. It cannot be like the normal Rmd we used
- ""
date: "2021-09-30"
description: Pay discrimination at Omega Group plc # the title that will show up once someone gets to this page
draft: false
image: pay_discrimination.jpg # save picture in \static\img\blogs. Acceptable formats= jpg, jpeg, or png . Your iPhone pics wont work

keywords: ""
slug: pay_discrimination # slug is the shorthand URL address... no spaces plz
title: Pay discrimination at Omega Group plc
---



<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>I am asked to carry out the analysis. The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))
glimpse(omega) # examine the data frame</code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, 635…
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;ma…
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24, 3…</code></pre>
</div>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender ?</h2>
<p>The data frame <code>omega</code> contains the salaries for the sample of 50 executives in the company. Can you conclude that there is a significant difference between the salaries of the male and female executives?</p>
<p>Note that you can perform different types of analyses, and check whether they all lead to the same conclusion</p>
<p>. Confidence intervals
. Hypothesis testing
. Correlation analysis
. Regression</p>
<pre class="r"><code># Confidence interval and hypothesis testing
t.test(omega %&gt;% 
         filter (gender == &#39;male&#39;) %&gt;%
         select (salary), 
      omega %&gt;%
      filter (gender == &#39;female&#39;) %&gt;%
      select (salary))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  omega %&gt;% filter(gender == &quot;male&quot;) %&gt;% select(salary) and omega %&gt;% filter(gender == &quot;female&quot;) %&gt;% select(salary)
## t = 4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   4420 12973
## sample estimates:
## mean of x mean of y 
##     73239     64543</code></pre>
<p>The p-value is close to 0, so we reject the null hypothesis, which means that we have strong evidence that mean salaries for men and women are different.</p>
<p>Also, confidence interval does not include 0, which again indicates that mean salaries between men and women are different.</p>
<pre class="r"><code># Correlation analysis
omega_num &lt;- omega %&gt;% 
mutate(gender_01 = ifelse(gender==&#39;male&#39;, 1, 0)) %&gt;% # convert gender to numerical variable
select(gender_01, salary) %&gt;% # select certain columns
cor()

omega_num</code></pre>
<pre><code>##           gender_01 salary
## gender_01     1.000  0.508
## salary        0.508  1.000</code></pre>
<p>Correlation coefficient is 0.508 indicates weak correlation between gender and salary.</p>
<pre class="r"><code># Regression
lm_omega &lt;- lm(formula = salary ~ gender, data = omega) # run a linear regression of salary on gender
summary(lm_omega)</code></pre>
<pre><code>## 
## Call:
## lm(formula = salary ~ gender, data = omega)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -18471  -4780    127   5484  14257 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    64543       1474   43.78  &lt; 2e-16 ***
## gendermale      8696       2128    4.09  0.00017 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7520 on 48 degrees of freedom
## Multiple R-squared:  0.258,  Adjusted R-squared:  0.243 
## F-statistic: 16.7 on 1 and 48 DF,  p-value: 0.000165</code></pre>
<p>R-squared is 0.258 (which is exactly correlation coefficient squared), which indicates that only 25% of variation in salary is explained by gender. Also, gendermale ciefficient is statistically significant.</p>
<p>Overall, we can say that there is evidence of correlation between gender and salary.</p>
<p>Calculate summary statistics on salary by gender. Also, create and print a dataframe where, for each gender, you show the mean, SD, sample size, the t-critical, the SE, the margin of error, and the low/high endpoints of a 95% condifence interval</p>
<pre class="r"><code># Summary Statistics of salary by gender
summary_stats &lt;- mosaic::favstats (salary ~ gender, data=omega)
summary_stats</code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, 
# the t-critical value, the standard error, the margin of error, 
# and the low/high endpoints of a 95% condifence interval

summary_stats %&gt;%
  mutate(t_crit = qt(0.95, df=n-1), std_err = sd/sqrt(n), margin_err=t_crit*sd/sqrt(n), low_end=mean-margin_err, high_end=mean+margin_err) %&gt;%
  select(gender, mean, sd, n, t_crit, std_err, margin_err, low_end, high_end)</code></pre>
<pre><code>##   gender  mean   sd  n t_crit std_err margin_err low_end high_end
## 1 female 64543 7567 26   1.71    1484       2535   62008    67078
## 2   male 73239 7463 24   1.71    1523       2611   70628    75850</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
</blockquote>
<p>Confidence intervals do not overlap, so we have strong evidence that mean salaries for men and women are different.</p>
<p>You can also run a hypothesis testing, assuming as a null hypothesis that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money. You should tun your hypothesis testing using <code>t.test()</code> and with the simulation method from the <code>infer</code> package.</p>
<pre class="r"><code># hypothesis testing using t.test() 
t.test(omega %&gt;% 
         filter (gender == &#39;female&#39;) %&gt;%
         select (salary), 
      omega %&gt;%
        filter (gender == &#39;male&#39;) %&gt;%
        select (salary))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  omega %&gt;% filter(gender == &quot;female&quot;) %&gt;% select(salary) and omega %&gt;% filter(gender == &quot;male&quot;) %&gt;% select(salary)
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean of x mean of y 
##     64543     73239</code></pre>
<pre class="r"><code># hypothesis testing using infer package
t_test(
  omega,
  formula =  salary ~ gender
)</code></pre>
<pre><code>## # A tibble: 1 × 7
##   statistic  t_df  p_value alternative estimate lower_ci upper_ci
##       &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1     -4.09  47.8 0.000165 two.sided     -8696.  -12973.   -4420.</code></pre>
<blockquote>
<p>What can you conclude from your analysis? A couple of sentences would be enough</p>
</blockquote>
<p>The p-values are less then 0.01, which indicates that there is strong evidence that mean salaries for women and men are different. The confidence interval for the mean is (-12973, -4420).</p>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender?</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience. A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of salary by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<p>Based on this evidence, can you conclude that there is a significant difference between the experience of the male and female executives? Perform similar analyses as in the previous section. Does your conclusion validate or endanger your conclusion about the difference in male and female salaries?</p>
<p>The standard deviation is pretty high, so we should definitely perform additional analyses to make a conclusion.</p>
<pre class="r"><code># Confidence interval and hypothesis testing
t.test(omega %&gt;% 
         filter (gender == &#39;male&#39;) %&gt;%
         select (experience), 
      omega %&gt;%
      filter (gender == &#39;female&#39;) %&gt;%
      select (experience))</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  omega %&gt;% filter(gender == &quot;male&quot;) %&gt;% select(experience) and omega %&gt;% filter(gender == &quot;female&quot;) %&gt;% select(experience)
## t = 5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   8.13 19.35
## sample estimates:
## mean of x mean of y 
##     21.12      7.38</code></pre>
<p>The p-value is close to 0, so we reject the null hypothesis, which means that we have strong evidence that mean experience for men and women are different.</p>
<p>Just as in case of salary, confidence interval does not include 0, which again indicates different mean experience for men and women.</p>
<pre class="r"><code># Correlation analysis
omega_num_exp &lt;- omega %&gt;% 
mutate(gender_01 = ifelse(gender==&#39;male&#39;, 1, 0)) %&gt;% # convert gender to numerical variable
select(gender_01, experience, salary) # select certain columns

omega_num_exp %&gt;%
select(gender_01, experience) %&gt;%
cor()</code></pre>
<pre><code>##            gender_01 experience
## gender_01      1.000      0.584
## experience     0.584      1.000</code></pre>
<p>Correlation coefficient of 0.584 indicates moderate correlation between gender and experience.</p>
<pre class="r"><code># Regression
lm_omega_2 &lt;- lm(formula = experience ~ gender_01, data = omega_num_exp) # run a linear regression of experience on gender
summary(lm_omega_2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = experience ~ gender_01, data = omega_num_exp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -20.12  -6.32  -2.25   8.37  22.88 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     7.38       1.91    3.87  0.00033 ***
## gender_01      13.74       2.76    4.98  8.5e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 9.74 on 48 degrees of freedom
## Multiple R-squared:  0.341,  Adjusted R-squared:  0.327 
## F-statistic: 24.8 on 1 and 48 DF,  p-value: 8.51e-06</code></pre>
<p>Base on the R-squared value, we can say that 32% of variation in experience is explained by variation in gender. If a person is male instead of a female, the mean experience is expected to be 13.74 years more (statistically significant), all else equal. I think this analysis might endanger the results of previous analyses because if experience varies a lot between genders, it might be that variation in salaries is actually explained by variation in experience and when we don’t include experience into the model, it captures partial effect through gender (omitted variable bias).</p>
<p>We can make a multiple regression model.</p>
<pre class="r"><code># Regression
lm_omega_2 &lt;- lm(formula = salary ~ gender_01 + experience, data = omega_num_exp) # run a linear regression of experience on gender
summary(lm_omega_2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = salary ~ gender_01 + experience, data = omega_num_exp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -13382  -3169   1100   3137  11521 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  60414.1     1176.3   51.36   &lt;2e-16 ***
## gender_01     1014.1     1826.4    0.56     0.58    
## experience     559.1       77.6    7.20    4e-09 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5240 on 47 degrees of freedom
## Multiple R-squared:  0.647,  Adjusted R-squared:  0.632 
## F-statistic: 43.1 on 2 and 47 DF,  p-value: 2.3e-11</code></pre>
<p>From this model we can see that when we include both experience and gender as independent variables, gender coefficient is not statistically significant but the coefficient for experience is. So when we omit the experience from the model, gender coefficient becomes sginificant while in reality it is not.</p>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience ?</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<p>Analyse the relationship between salary and experience. Draw a scatterplot to visually inspect the data</p>
<pre class="r"><code>ggplot(data = omega, aes(x = experience, y = salary))+
  geom_point(alpha=0.3) +
  geom_smooth(method = &quot;lm&quot;) + 
  theme_bw() +
  labs(title = &quot;Relationship between salary and experience&quot;, x = &quot;Experience in years&quot;, y=&quot;Yearly salary in $&quot;)</code></pre>
<p><img src="/blogs/pay_discrimination_files/figure-html/salary_exp_scatter-1.png" width="648" style="display: block; margin: auto;" />
It seems like there is a positive relationship between experience and salary.</p>
<pre class="r"><code># Regression
lm_omega_2 &lt;- lm(formula = salary ~ experience, data = omega_num_exp) # run a linear regression of experience on gender
summary(lm_omega_2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = salary ~ experience, data = omega_num_exp)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -13516  -2926    634   2952  11997 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  60549.0     1142.6   52.99  &lt; 2e-16 ***
## experience     584.3       62.6    9.34  2.3e-12 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5200 on 48 degrees of freedom
## Multiple R-squared:  0.645,  Adjusted R-squared:  0.638 
## F-statistic: 87.2 on 1 and 48 DF,  p-value: 2.26e-12</code></pre>
<p>The regression model confirms strong positive relationship as well. On average, additional year of experience increases yearly salary by $584.</p>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>You can use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make ths plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  select(gender, experience, salary) %&gt;% #order variables they will appear in ggpairs()
  ggpairs(aes(colour=gender, alpha = 0.3))+
  theme_bw()</code></pre>
<p><img src="/blogs/pay_discrimination_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Look at the salary vs experience scatterplot. What can you infer from this plot? Explain in a couple of sentences</p>
</blockquote>
<p>We see a positive correlation between salary and experience. The reason why we initially thought there was pay discrimination is because, on average, women have less experience (more pink dots on the left) and men have more (more blue dots on the right).</p>
</div>
</div>
